[package]
name = "oauth2-proxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"
serde_json = "1.0"

reqwest = { version = "0.11", features = ["json"] }

hmac = "0.11.0"
sha2 = "0.9.5"

structopt = "0.3"
thiserror = "1.0"

rocket = { version = "0.5.0-rc.1", features = ["secrets"] }

askama = { git = "https://github.com/djc/askama" }
askama_rocket = { git = "https://github.com/djc/askama" }

chrono = "0.4"

# redis = { version = "0.20.2", features = ["tokio-comp"] }
rusoto_core = "0.46.0"
dynomite = { git = "https://github.com/softprops/dynomite", rev = "16c61ae635f0ea182709f64f1f47afa45e3561a8" }

async-trait = "0.1.50"

uuid = "0.8"
base64 = "0.13"

toml = "0.5.8"

rand = "0.8.4"
time = "0.2"
