[package]
name = "oauth2-proxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }

oauth2 = "4.1.0"

hmac = "0.11.0"
sha2 = "0.9.5"

structopt = "0.3"

warp = "0.3.1"
http = "0.2"

askama = { version = "0.10", features = ["with-warp"] }
askama_warp = "0.11"

tracing = "0.1"
tracing-subscriber = "0.2"

chrono = "0.4"

# redis = { version = "0.20.2", features = ["tokio-comp"] }
rusoto_core = "0.47.0"
rusoto_dynamodb = "0.47.0"
serde_dynamodb = { version = "0.9.0", default_features = false, features = ["native-tls"] }

async-trait = "0.1.50"
